// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjbfC37gDITpROcPrR7GIeJ9TJD6jGzec',
    appId: '1:892914047958:web:fcbd9ad20a89277177e277',
    messagingSenderId: '892914047958',
    projectId: 'kivaloop-fc52e',
    authDomain: 'kivaloop-fc52e.firebaseapp.com',
    storageBucket: 'kivaloop-fc52e.firebasestorage.app',
    measurementId: 'G-HXLXLHL4B4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIBGvsjBxVS0CEkd7KVUGhgdTp1ca7nsw',
    appId: '1:892914047958:android:fce334f131deff0377e277',
    messagingSenderId: '892914047958',
    projectId: 'kivaloop-fc52e',
    storageBucket: 'kivaloop-fc52e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuGVUbTBh6DOvbZlrc_xG_w0MafpOwvxg',
    appId: '1:892914047958:ios:865f35e2ccc5702477e277',
    messagingSenderId: '892914047958',
    projectId: 'kivaloop-fc52e',
    storageBucket: 'kivaloop-fc52e.firebasestorage.app',
    iosBundleId: 'com.example.kivaloop',
  );
}
